/**
 * @license
 * [BSD-3-Clause](https://github.com/pryv/lib-js/blob/master/LICENSE)
 */
/**
 * One-off generator for `ecies-aes-256-gcm.json` — a known-answer DECRYPT
 * vector for the asymmetric `ecies-aes-256-gcm` method.
 *
 * The wire format is FROZEN (published in the event-type registry):
 *
 *   payload = base64( ephemeralPublicKey[65, SEC1 uncompressed 0x04||X||Y]
 *                     || iv[12] || ciphertext || tag[16] )
 *
 * Encryption steps:
 *   1. ECDH(ephemeral private, recipient public) -> 32-byte shared secret.
 *   2. HKDF-SHA-256(secret, salt = <empty>, info = ASCII "encrypted/ecies-aes-256-gcm"),
 *      length 32 -> AES-256-GCM key.
 *   3. AES-256-GCM(plaintext, key, iv) where plaintext = UTF-8 JSON of material.
 *
 * To make the vector reproducible and byte-exact, BOTH the recipient and the
 * ephemeral key pairs, the 12-byte IV and the plaintext are FIXED here (the
 * runtime `encrypt` uses a random ephemeral + random IV by design, which the
 * round-trip tests cover separately). Generation runs on Node's WebCrypto; the
 * emitted vector is plain JSON.
 *
 * Run: `node components/pryv-encryption/test/fixtures/generate-ecies.js`
 */
'use strict';

const { webcrypto } = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const subtle = webcrypto.subtle;
const INFO = 'encrypted/ecies-aes-256-gcm';

// Fixed recipient key pair (P-256, JWK).
const RECIPIENT = {
  publicKey: {
    kty: 'EC',
    crv: 'P-256',
    x: 'vN2pTQ7eQd3gDo9E9-T6XlK4J7nkkHDNPo5CEi54nIg',
    y: 'v-noMfXE5bc8WQr7DLUVMw186XLeYnqNEyZEBacQnes'
  },
  privateKey: {
    kty: 'EC',
    crv: 'P-256',
    x: 'vN2pTQ7eQd3gDo9E9-T6XlK4J7nkkHDNPo5CEi54nIg',
    y: 'v-noMfXE5bc8WQr7DLUVMw186XLeYnqNEyZEBacQnes',
    d: 'kCm5Pa7sj_7firW_nild7COqV0eR3vI5ofaBJTRY3h4'
  }
};

// Fixed ephemeral key pair (P-256, JWK).
const EPHEMERAL = {
  publicKey: {
    kty: 'EC',
    crv: 'P-256',
    x: 'itduLILJK0LFNFSX4DJGsJveY0eMALL72we3KH38VDs',
    y: 'XkK7ZETz45gBXbDDJS7QXpFKxLBQngvw8J29dDj04C4'
  },
  privateKey: {
    kty: 'EC',
    crv: 'P-256',
    x: 'itduLILJK0LFNFSX4DJGsJveY0eMALL72we3KH38VDs',
    y: 'XkK7ZETz45gBXbDDJS7QXpFKxLBQngvw8J29dDj04C4',
    d: 'Dm1NsoliiiaCF6PvfQMupI4a1FJ8UQhfy2faUXtYxU4'
  }
};

// Fixed 12-byte IV and plaintext material.
const IV = new Uint8Array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]);
const MATERIAL = { type: 'note/txt', content: 'an asymmetric secret note' };

function bytesToBase64 (bytes) {
  let bin = '';
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return Buffer.from(bin, 'binary').toString('base64');
}

async function main () {
  // ECDH(ephemeral private, recipient public) -> 32-byte shared secret.
  const ephPriv = await subtle.importKey('jwk', EPHEMERAL.privateKey, { name: 'ECDH', namedCurve: 'P-256' }, false, ['deriveBits']);
  const recipPub = await subtle.importKey('jwk', RECIPIENT.publicKey, { name: 'ECDH', namedCurve: 'P-256' }, false, []);
  const secretBits = await subtle.deriveBits({ name: 'ECDH', public: recipPub }, ephPriv, 256);
  const secret = new Uint8Array(secretBits);

  // HKDF-SHA-256 -> AES-256-GCM key.
  const hkdfKey = await subtle.importKey('raw', secret, 'HKDF', false, ['deriveBits']);
  const aesBits = await subtle.deriveBits(
    { name: 'HKDF', hash: 'SHA-256', salt: new Uint8Array(0), info: new TextEncoder().encode(INFO) },
    hkdfKey,
    256
  );
  const aesKey = await subtle.importKey('raw', new Uint8Array(aesBits), 'AES-GCM', false, ['encrypt']);

  // AES-256-GCM encrypt.
  const plaintext = new TextEncoder().encode(JSON.stringify(MATERIAL));
  const cipherBuf = await subtle.encrypt({ name: 'AES-GCM', iv: IV }, aesKey, plaintext);
  const cipherBytes = new Uint8Array(cipherBuf);

  // Ephemeral public key as raw SEC1 uncompressed (65 bytes: 0x04 || X || Y).
  const ephPub = await subtle.importKey('jwk', EPHEMERAL.publicKey, { name: 'ECDH', namedCurve: 'P-256' }, true, []);
  const ephRaw = new Uint8Array(await subtle.exportKey('raw', ephPub));
  if (ephRaw.length !== 65 || ephRaw[0] !== 0x04) {
    throw new Error('unexpected ephemeral public key raw encoding');
  }

  const out = new Uint8Array(ephRaw.length + IV.length + cipherBytes.length);
  out.set(ephRaw, 0);
  out.set(IV, ephRaw.length);
  out.set(cipherBytes, ephRaw.length + IV.length);

  const fixture = {
    description: 'Known-answer decrypt vector for ecies-aes-256-gcm. payload = base64(ephemeralPublicKey[65] || iv[12] || ciphertext || tag[16]); AES-256-GCM key = HKDF-SHA-256(ECDH(ephemeral, recipient), salt=<empty>, info="' + INFO + '"). Recipient + ephemeral key pairs, IV and plaintext are all fixed. Generated by generate-ecies.js (Node WebCrypto).',
    recipient: RECIPIENT,
    ephemeral: EPHEMERAL,
    ivBase64: bytesToBase64(IV),
    plaintextObject: MATERIAL,
    plaintextJson: JSON.stringify(MATERIAL),
    payload: bytesToBase64(out)
  };

  const target = path.join(__dirname, 'ecies-aes-256-gcm.json');
  fs.writeFileSync(target, JSON.stringify(fixture, null, 2) + '\n');
  console.log('wrote', target);
}

main().catch((e) => { console.error(e); process.exit(1); });
